import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import { Button } from "@/components/ui/button";
import { NavItem } from "@/components/nav-item";
import Link from "next/link";
import Image from "next/image";
import { MobileNav } from "@/components/mobile-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen bg-[#0e0e0f] text-white font-sans antialiased overflow-x-hidden">
        {/* NAVBAR */}
        <header className="w-full bg-[#0e0e0f] border-b border-[#23242b] py-0 px-0 sticky top-0 z-50">
          <nav className="max-w-7xl mx-auto flex items-center justify-between px-4 py-4">
            {/* Logo */}
            <div className="flex items-center gap-3">
              <Link href="/" className="flex items-center">
                <Image
                  src="/uploads/datan8-logo.png"
                  width={215}
                  height={60}
                  alt="DataN8 Logo"
                  className="h-8 w-auto sm:h-9 md:h-10 lg:h-12 xl:h-14"
                  priority
                  quality={100}
                />
              </Link>
            </div>

            {/* Desktop Navigation */}
            <div className="hidden lg:flex gap-8 text-lg font-bold items-center">
              <NavItem href="/" text="Home" />
              <NavItem text="Services" dropdown />
              <NavItem href="/about" text="About" />
              <NavItem href="/blog" text="Blog" />
              <NavItem href="/contact" text="Contact" />
            </div>

            {/* Desktop CTA Button */}
            <div className="hidden lg:block">
              <Link href="/contact">
                <Button className="px-8 py-3 h-12 bg-[#00FFF7] hover:bg-[#00E5DE] text-black font-semibold uppercase tracking-wide rounded shadow-lg text-base">
                  Get in Touch
                </Button>
              </Link>
            </div>

            {/* Mobile Navigation */}
            <div className="lg:hidden">
              <MobileNav />
            </div>
          </nav>
        </header>

        {/* MAIN CONTENT */}
        <ClientBody>{children}</ClientBody>

        {/* FOOTER */}
        <footer className="bg-[#0e0e0f] pt-12 pb-6 text-white">
          <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row gap-10">
            {/* Logo + Desc */}
            <div className="flex-1 min-w-[200px] mb-6 md:mb-0">
              <div className="flex items-center mb-6">
                <Image
                  src="/uploads/datan8-official-logo.png"
                  width={215}
                  height={60}
                  alt="DataN8 Logo"
                  className="h-8 w-auto sm:h-9 md:h-10 lg:h-12 xl:h-14"
                  priority
                  quality={100}
                />
              </div>
              <ul className="text-zinc-400 text-sm mb-4">
                <li className="mb-1">
                  Auckland-based AI, technology & automation partner for ambitious NZ businesses.
                </li>
                <li className="mb-1">
                  Remote-first consulting, implementation, hosting, & more.
                </li>
                <li>100% Kiwi owned.</li>
              </ul>
            </div>
            {/* Site Nav */}
            <div className="flex-1 min-w-[180px] mb-6 md:mb-0">
              <div className="font-semibold mb-4">Navigation</div>
              <ul className="space-y-1 text-zinc-300 text-sm">
                <li>
                  <Link href="/" className="hover:text-[#00FFF7] transition">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/services" className="hover:text-[#00FFF7] transition">
                    Services
                  </Link>
                </li>
                <li>
                  <Link href="/about" className="hover:text-[#00FFF7] transition">
                    About
                  </Link>
                </li>
                <li>
                  <Link href="/blog" className="hover:text-[#00FFF7] transition">
                    Blog
                  </Link>
                </li>
                <li>
                  <Link href="/contact" className="hover:text-[#00FFF7] transition">
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
            {/* Services */}
            <div className="flex-1 min-w-[180px] mb-6 md:mb-0">
              <div className="font-semibold mb-4">Services</div>
              <ul className="space-y-1 text-zinc-300 text-sm">
                <li>
                  <Link href="/services/ai-automation-strategy" className="hover:text-[#00FFF7] transition">
                    AI & Automation Consulting
                  </Link>
                </li>
                <li>
                  <Link href="/services/ai-agents" className="hover:text-[#00FFF7] transition">
                    AI Agents
                  </Link>
                </li>
                <li>
                  <Link href="/services/website-creation" className="hover:text-[#00FFF7] transition">
                    Website Creation
                  </Link>
                </li>
                <li>
                  <Link href="/services/document-ingest" className="hover:text-[#00FFF7] transition">
                    Document Ingest
                  </Link>
                </li>
                <li>
                  <Link href="/services/digital-services" className="hover:text-[#00FFF7] transition">
                    Digital Services
                  </Link>
                </li>
                <li>Hosting</li>
              </ul>
            </div>
            {/* Contact */}
            <div className="flex-1 min-w-[220px]">
              <div className="font-semibold mb-4">How to contact</div>
              <ul className="text-sm text-zinc-300 mb-4 space-y-1">
                <li>
                  <span className="text-[#00FFF7]">Phone:</span>{" "}
                  <a href="tel:+6498840994" className="hover:text-[#00FFF7]">
                    +64 9 884 0994
                  </a>
                </li>
                <li>
                  <span className="text-[#00FFF7]">Email:</span>{" "}
                  <a
                    href="mailto:team@datan8.co.nz"
                    className="hover:text-[#00FFF7]"
                  >
                    team@datan8.co.nz
                  </a>
                </li>

              </ul>
              <Link href="/contact">
                <Button className="bg-[#00FFF7] text-black font-semibold hover:bg-[#00E5DE] w-full rounded shadow">
                  Get in Touch
                </Button>
              </Link>
              <div className="flex space-x-2 mt-3">
                <a
                  href="https://www.linkedin.com/company/datan8"
                  aria-label="LinkedIn"
                  className="hover:text-[#00FFF7]"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  LinkedIn
                </a>
                {/* Add or update links as needed */}
              </div>
            </div>
          </div>
          {/* Copyright Bottom Row */}
          <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row justify-between items-center border-t border-[#23242b] pt-6 mt-10 text-xs text-zinc-400">
            <div>© 2025 DataN8. All rights reserved.</div>
            <div className="flex space-x-4 mt-2 md:mt-0">
              <Link href="/privacy" className="hover:text-[#00FFF7]">
                Privacy Policy
              </Link>
              <Link href="/terms" className="hover:text-[#00FFF7]">
                Terms of Use
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
